### ISSUE TITLE
New Enhancements, Enhancement Adjustments

### ISSUE THREAD

**Issue by Valo56** [zunath/SWLOR_NWN#1505]
For the brave among us. Or for myself if someone can briefly walk me through how to do it.

I'd like us to have the following enhancement properties added to the toolset:
For everything:
Force Attack

For Weapons:
Accuracy

For Armor:
Accuracy
Attack

I would like to do the following:
Provide +Accuracy enhancements for weapons, scaling up to +5 at t5.

Provide +Accuracy enhancements for armor, scaling up to +3 at t5 (+1 at t1, +2 at t3, +3 at t5).

Provide +Attack and +Force Attack enhancements for weapons and armor, scaling to +5 at t5.

Increase scaling for evasion, force and physical defense enhancements on armor by +3 per tier (+8 total at t5)

Reasoning:
The defensive slant to SWLOR combat is good and should not change.

But these changes, taken as a whole, will allow for players to begin to set up gear specifically to fulfill a DPS role. Defensive enhancements will remain more impactful overall and the generally slow pace of combat will not be overly changed.

This has the advantage in that players can more effectively build for and prepare for fights against high defense/evasion enemies. Players can also focus purely into sorcerer/devices builds by putting everything into force attack/attack respectively.

I can get everything set up in terms of recipes and items. I'll just need help figuring out how to add the item properties themselves to the toolset/module unless someone else can manage that.

**Comment by zunath** [comment]
@JohnWildkins - Would like your insight to how this would play with your rebalance patch.

**Comment by JohnWildkins** [comment]
> @JohnWildkins - Would like your insight to how this would play with your rebalance patch.

My initial gut reaction is that it will affect most things equally, but it might slant hard toward things like TWF / twin blades that have an inherent (although reduced) to-hit penalty. That being said, +5 accuracy and +3 on armor isn't insanely massive, and if someone specs into that over defense to get more DPR I don't see a huge problem

I'm a little leery about +ATK (especially +5 on armor), because I think that might get out of hand fast. Bear in mind that Force Rage 2 is one of the strongest abilities on the server right now in terms of raw DPR increase, and that's +20 ATK. Again, you're sacrificing defense to make this happen, but a theoretical... +40, +45 ATK would be a pretty zany increase in DPR. I'm not sure how much that would break something like a naturally tanky AGI/PER/VIT build

**Comment by Valo56** [comment]
The +5 ATK on armor would be overshadowed by the buffs to defensive enhancements, and we would retain the defensive slant to things that currently exists. I'm planning to update event NPC's and redo Dathomir NPC's as well, and slight tweaks to the skins of other world creatures would not be terribly hard or time consuming if they proved necessary.
