### ISSUE TITLE
Self-Targeting Armor and Shield Repairers

### ISSUE THREAD

**Issue by Valo56** [zunath/SWLOR_NWN#1584]
With my space encounters update I tried to get it working such that players could target themselves with repair modules but I couldn't get it to work.

This would be a great addition though.

If anyone is able to make this fix/addition it'd be a great addition. (Side note a rest option in space to rapidly regen capacitor/shields and slowly regen armor would be great.) I'd really like to start adding dungeon type areas in space and players would probably need the ability to use these in order to handle prolonged fighting like that without requiring dedicated support ships.

**Comment by zunath** [comment]
Targeting is based on NWN attack mechanics. You cannot attack yourself in NWN.

The closest we can get to a self-repair is a specific ship module which only targets yourself on use. I would prefer this to a standard rest option since it forces the player to make decisions about their build moreso than a rest option.

**Comment by Valo56** [comment]
What's a general checklist for what all needs done to get these in? I figure maybe two variants, a low cap use regen and a high cap use burst heal, would be nice. I might see what I can do. Does it need hak updates since they'd show up in class abilities?

**Comment by zunath** [comment]
Should just be code changes. I would look at how the current repairers work and add a new type which doesn't require a target.
