### ISSUE TITLE
Balance : Respawn time in Maintenance level, Mando facility, Viscara Wildlands...

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#214]
Respawn time for the mobs definitely needs to be increased.

Went to the Mando facility yesterday, there were 2 of us. Mandalorians have enough time to respawn at least 1 time if you know perfectly the patch to follow, and if you struggle to find your way and the key cards, they may even respawn 2 times...Which is ridiculous.

I think that every quest involved area should have a respawn time high enough to avoid any respawn when a player is following the quest there...

In Maintenance Level, it means removing some robots and adding a few mynocks, to be sure players don't have to wait for them to respawn to complete quest.

In Viscara Wildlands/Wildwoods, there are already enough mobs to kill to do the quest in one shot.

**Comment by zunath** [comment]
I think these are on an 8 minute respawn timer which I thought was long already. I'm curious about when the respawns hit you. Was it on your way back from getting one of the key cards? Or did it happen while you were fighting another enemy?

I'm questioning whether the respawns are the problem or if it's because the fights are too long due to enemy stats, lack of viable gear options, or some other reason. I don't want to just increase the respawn timer because I think there may be another underlying issue at play here.

**Comment by zunath** [comment]
I definitely want to have longer fights than typical NWN because it enables players to use the enmity system as well as the other perks. 30 seconds seems reasonable to me. I'm actually pretty happy to hear you're able to see improvement after playing a bit.

I've dropped the number of enemies you need to kill for the quests (that was part of another ticket). So knowing all of this, I think maybe increasing the spawn times actually makes some sense. We can try it and see.

**Comment by zunath** [comment]
I bumped up the respawn times in the Mandalorian facility. I'm interested to hear your feedback on it. If it goes well, we can do the same for the other dungeons

**Comment by extaz93** [comment]
I'll wait for someone to crawl into the Mando facility with me to see how the new respawn works with a 2 players team.
