### ISSUE TITLE
[Enhancement] Add more portraits variety

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#342]
Add some portraits for players and NPC's :

- Bith (0 for now)
- Kel'Dor (0 for now)
- Bothan (only 1 for now)
- Weequay (0 for now)
- Rodian (0 for now)
- Some factions logos (Republic, Sith, Czerka, Mandos, Hutts) for NPC's, so we won't have to bother too much sometimes to choose a portrait.

Chiss, Wookies, Trandoshans, Twi'leks, Zabraks and Humans seems ok for now.

**Comment by zunath** [comment]
I need someone to run down getting graphics for these.

**Comment by zunath** [comment]
I'm actually going to close out this ticket because there isn't a specific action to take on it. When we've gotten actual portrait files to implement, open up another ticket with a download link to the files and we'll add it. Otherwise, this belongs on Trello as a "we need to do it, but don't have the required stuff yet". I'll make a Trello ticket for it.
