### ISSUE TITLE
GAME: Redone Mando Base

### ISSUE THREAD

**Issue by Ashmiet** [zunath/SWLOR_NWN#357]
https://cdn.discordapp.com/attachments/505400487118372864/508128019211223042/redone_manda_facilit001.rar

**Comment by zunath** [comment]
https://cdn.discordapp.com/attachments/500327492154818571/506690885887590400/unknown.png

**Comment by zunath** [comment]
Few things I noticed we need to address before releasing this:

1.) The area is a copy of the existing area. We need to delete the old area, and set the new area's resref to the old one in order to maintain persistent locations.
2.) The doors are locked but not plot which means players can just bash them open. They also aren't set up to accept the key items found in the area. Need to fix it so that you open them with the keys (or keep the old mechanic of requiring all three keys in order to open the boss door).
3.) I still can't find the spawn point for the boss. I'm not sure if it's gone or I just missed it.

**Comment by zunath** [comment]
Fixed the door and I found the boss room. Should be good now.
