### ISSUE TITLE
GAME: Flooring conflicts with the placeable ground cover in apartments

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#502]
Carpet: Red does not appear when the furniture object is used to place it

Phylaverian	apartment_2	19.703332901001	17.4114513397217	0

**Comment by CragOrion** [comment]
Noticed this also. The rug does not appear on the floor, and when you use the furniture object to view the list of nearby furniture, it does not appear on the list, but if you use the item and hit preview to show the count of fixtures, it still counts it in the maximum allowed fixtures as if it was placed

**Comment by CragOrion** [comment]
I forgot to mention above that for me, it happens for the Blue carpet. Before I'd tried it in the small apartment. Now I tried it again this time in a small building. It still doesnt show and still takes up a fixture slot. It does kind of show on the list of nearby structures when you use the item, though not under its name. It shows on the list as "Continue" but if you try to select it and then say pick it up, it wont pick it up, it will just keep having you click to confirm pickup, Is it possible to at least get the database edited for my building so that its not taking up a furniture slot?

Thanks

**Comment by NZNightwolf** [comment]
I have, possibly, discovered what this glitch is. There are two types sizes of floor covers in the module currently: FloorCover: RugL_xxx (ARF)* and FloorCover: RugS_xxx (ARF)*.

The FloorCover: RugS_xxx (ARF)* need to be raised 0.01 or 0.02 on the Z axis via the toolset to become unglitched in the ground, where the FloorCover: RugL_xxx (ARF)* sit above the ground naturally. Unsure if this is an easy fix.

**Comment by givemedeath** [comment]
Might be good to implement z-axis movement via the edit function in the structure management tool.
This would also allow furniture and decorations to be stacked.
Is this something that would be likely to be abused?

**Comment by zunath** [comment]
Not sure. Considering it only affects the interior of people's houses I think it might be fine to give to the players. Just need to clamp down the min/max positions.
