### ISSUE TITLE
GAME: Change the color of the OOC speech

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#566]
It's almost impossible to read the OOC channel on a lot of backgrounds. Look at changing the color of the text to make it more readable.

**Comment by Liareth** [comment]
Feel free to change this if you want, but I intentionally made it dark to encourage people NOT to use it!

**Comment by Kenji3108** [comment]
Before I joined Arelith, I never had problems with OOC chat in an RP environment. Ever since I did and realized how much more immersive an RP session can be without OOC in chat, I avoided using those at all costs, would rather resort to tells than outright breaking character.

It's something to take note of for an RP server, I actually found it hard to enjoy any other RP server if they don't actively discourage the use of OOC in chat.

**Comment by Liareth** [comment]
Same, really. If I come across someone using OOC chat in the world I tend to nope out of there ASAP.
