### ISSUE TITLE
GAME: RP Experience 

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#689]
Look into a way to gain Experience that pools into a general section that a player could then use to put into  any skill. This would of course have to be capped so a player can't just spam, and lower amounts, but would still be passive Experience to encourage RP.

Further more with the above put in add a way to a make it so players can choose a way to fully use the system to level vs the normal mechanics. The experience gains would of course be buffed over the normal. And they would no longer gain experience from the typical sense.

**Comment by zunath** [comment]
I kind of envisioned this working with the RP token system where people could purchase XP books with the tokens they acquire. Unless you're talking about an automated system where players get XP automatically through RP?

**Comment by taelon875** [comment]
An automated system.

**Comment by Couls** [comment]
How would it be automated? Would we check if the player is chatting and in vicinity of others?

**Comment by taelon875** [comment]
Sort of working like the chat system, but it gives exp into a pool. Something that wouldn't be major but would pool up over time.

**Comment by zunath** [comment]
I'm totally in favor of this. I'd recommend adding menu options to the Skills menu which allows you to distribute the pooled XP into the skill(s) of your choice. No reason to have a separate menu for it.

I'd suggest looking into how other servers do this and prevent spam from occurring. We would still need to police people though.

**Comment by Ryudo700** [comment]
Which version of the Arelith RPR system do you propose? The one where you had adventuring XP or without? Because I feel like removing adventuring XP from that system will do better. The Adventuring XP ended up making power leveling so viable from abusing it that it wasn't even funny, but flat RPR would work, especially with a rating that DM's can give which encourage players to RP more.

The second idea is great but how are you going to make flags or checks to stop people from abusing it? You could in theory gain XP by talking in a house away from people all day every day without RP this way. Atleast with RPR you can do AFK checks in the code to stop people trying to farm it all day, and the amount gained is much less then actually going out and doing the work yourself, atleast it was in Arelith.

**Comment by Mithreas** [comment]
I was thinking no adventuring xp, but I don't mind. 

On the second idea, the whole point is that you can check that *someone else* is talking to you.  i.e. you can hook the chat scripts so that if the listener and speaker are two different PCs, you do something.

**Comment by zunath** [comment]
https://cdn.discordapp.com/attachments/438788488985444362/555413063134740501/rpxp.nss

^ Script used on another server. We'll want to convert this to C#, hook up an XP pool, and allow players to distribute the XP to individual skills.

**Comment by zunath** [comment]
Implemented in #866
