### ISSUE TITLE
GAME: Scavenge on Coxxion Supplies Crates

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#722]
Despite succeedong on 2 scavenging attempts, this box only gives 1 item. This issue occurs continuously with this box even in a new instance. The other boxes don't seem to have this issue	Coxxion Supplies Crate	v_cox_base	36.5297355651855	60.2870330810547	-0.5

**Comment by zunath** [comment]
Despite succeeding on both scavenger checks, this box gave nothing.	Coxxion Supplies Crate	v_cox_base	48.2179260253906	86.9438171386719	0	232.478424072266

**Comment by Mithreas** [comment]
I believe the issue is that nw_it_ld001 exists in both loot table 39 (instance) and 40 (supply crates) but doesn't have a blueprint in the module.  If you know what this is meant to be I can send you a fixed blueprint - or I can fix the database and send you a migration script.  Let me know what you'd rather.

**Comment by zunath** [comment]
I think this was the gold item? I'm not positive, but you probably need to find the gold piece in the standard palette, place it down in the world, right click the object and go to properties to get the resref. 

If the resref is correct then we probably need to look into having a way for loot tables spawn gold.

**Comment by Mithreas** [comment]
Correct resref for gold item is nw_it_gold001

(You can use “show preview window” in the View menu to see it directly from the palette).

I’ll update the live database now and test.  Assuming it works, I will send you a migration script.
