### ISSUE TITLE
GAME: Denam Reyholm promotes METAGAMING!

### ISSUE THREAD

**Issue by LordGoogle** [zunath/SWLOR_NWN#825]
But seriously. Denam Reyholm the quest giver outside the Caxxion base gives you a bunch of directions, one of them being to give his name to the next contact only... He never actually tells you his name in character. Clearly the best course of action is to ban anyone that has completed this quest for Metagaming. Except for me, because I reported it, right?

**Comment by zunath** [comment]
I suppose it depends on how much of a stickler you are with NPC conversations. I always assumed most of he pleasantries ("Nice to meet you, I'm so and so" "Ah yes, the weather is lovely today!" "Oh, you have a family?" etc etc) were just assumed to have happened. In general I'd just say "whatever" but since the quest requires you to actually mention his name we should also include it in the conversation.
