### ISSUE TITLE
GAME: Parry Mode

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#877]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

2F80481D-A5FC-4B53-9A2E-4C5380DE4D41 | 94101C3A-D59D-4A76-B7D0-0E8CAA40BAAA | QRHPRN4P | Parry mode can be used! | Hanabea Petipay | viscaradeepmount | 46.99084091 | 40.77654648 | 0.07132845372 | 46.0269928 | 2019-04-02 22:25:22

**Comment by givemedeath** [comment]
Believe this requires using the NWNX_CombatModes plugin in conjunction with NWNX_Events.
Is NWNX_CombatModes in use here currently?

**Comment by NZNightwolf** [comment]
2F80481D-A5FC-4B53-9A2E-4C5380DE4D41 | 94101C3A-D59D-4A76-B7D0-0E8CAA40BAAA | QRHPRN4P | Parry mode can be used! | Hanabea Petipay | viscaradeepmount | 46.99084091 | 40.77654648 | 0.07132845372 | 46.0269928 | 2019-04-02 22:25:22 | 398

**Comment by zunath** [comment]
Some of the players brought up a good point that parry prevents your character from attacking back automatically, which is beneficial to the force users. There's no other way, to my knowledge, to keep that from happening. I'd probably lean on the side of keeping it in place since it does serve a purpose.

**Comment by zunath** [comment]
I think we'll go ahead and leave this in place.
