### ISSUE TITLE
GAME: Space Landing

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#904]
Game needs to do a check to see if hull is destroyed to see if landing is possible. And if hull is destroyed we need some kind of Ejection Pod to place player back down on planet. (This might be worth it over all for all deaths in space.)

**Comment by zunath** [comment]
This is a wider conversation we probably need to have about what to do with ships who get destroyed. Likely should destroy most, if not all, items on board... I'm pretty sure Mith left this functionality out from the start because we weren't entirely sure the system would work perfectly. I think at this point it's safe to say it's time to put this in.

**Comment by zunath** [comment]
Space system got a rewrite in the revamp which involves losing your ship when it's destroyed.
