### ISSUE TITLE
GAME: Throwing Point Blank Shot

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#986]
Throwing could use point blank shot, -4 ab is killer when things get close.

**Comment by zunath** [comment]
I'm on the fence about this one. As we discussed in-game, throwing is already a powerful skill due to it's DEX primary and STR secondary. I feel like one of the downsides of using throwing weapons versus blasters is that you have to actually be out of melee range. Otherwise players are incentivized to always use throwing weapons over blasters.

**Comment by zunath** [comment]
Moreover, the throwing skill is going to be getting grenades at some point in the near future(TM), so I definitely feel like keeping PBS off of it is the right move. That being said, they probably should get something early on to help new players out.

**Comment by taelon875** [comment]
Maybe change precise shot to have a % chance to trigger a bleeding instead.
